import { useState, useEffect, useCallback } from "react";
import { Zap, Trash2, RefreshCw, Shield, AlertCircle } from "lucide-react";

const API = import.meta.env.VITE_API_URL || "";

function severityColor(s) {
  if (!s) return "text-slate-400 bg-slate-800 border-slate-700";
  const u = s.toUpperCase();
  if (u === "CRITICAL") return "text-red-300 bg-red-900/40 border-red-700/50";
  if (u === "HIGH")     return "text-orange-300 bg-orange-900/40 border-orange-700/50";
  if (u === "MEDIUM")   return "text-yellow-300 bg-yellow-900/40 border-yellow-700/50";
  return "text-green-300 bg-green-900/40 border-green-700/50";
}

function timeAgo(ts) {
  if (!ts) return "—";
  const diff = Math.floor(Date.now() / 1000 - ts);
  if (diff < 60)    return `${diff}s ago`;
  if (diff < 3600)  return `${Math.floor(diff / 60)}m ago`;
  if (diff < 86400) return `${Math.floor(diff / 3600)}h ago`;
  return `${Math.floor(diff / 86400)}d ago`;
}

export default function AdaptiveRulesPanel() {
  const [rules, setRules]       = useState([]);
  const [loading, setLoading]   = useState(true);
  const [deleting, setDeleting] = useState(null);
  const [stats, setStats]       = useState({ active: 0, total: 0 });

  const fetchRules = useCallback(async () => {
    try {
      const res = await fetch(`${API}/api/adaptive-rules`);
      const data = await res.json();
      setRules(data.rules || []);
      setStats({ active: data.active || 0, total: data.total || 0 });
    } catch (_) {
      // silently fail — Redis may not have any rules yet
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    fetchRules();
    const id = setInterval(fetchRules, 30_000);
    return () => clearInterval(id);
  }, [fetchRules]);

  const handleDelete = async (rule_id) => {
    setDeleting(rule_id);
    try {
      await fetch(`${API}/api/adaptive-rules/${rule_id}`, { method: "DELETE" });
      setRules((prev) => prev.filter((r) => r.rule_id !== rule_id));
      setStats((prev) => ({ ...prev, active: Math.max(0, prev.active - 1), total: Math.max(0, prev.total - 1) }));
    } catch (_) {}
    setDeleting(null);
  };

  const activeRules   = rules.filter((r) => r.status === "active");
  const rejectedRules = rules.filter((r) => r.status === "rejected");

  return (
    <div className="bg-slate-900 rounded-2xl border border-slate-800 p-5">
      {/* Header */}
      <div className="flex items-center justify-between mb-4">
        <div className="flex items-center gap-3">
          <div className="w-8 h-8 rounded-lg bg-purple-500/20 border border-purple-500/30 flex items-center justify-center">
            <Zap className="w-4 h-4 text-purple-400" />
          </div>
          <div>
            <h3 className="font-semibold text-slate-200 text-sm">Adaptive Rules</h3>
            <p className="text-xs text-slate-500">Auto-generated by Claude · live in Layer 1</p>
          </div>
        </div>
        <div className="flex items-center gap-3">
          <div className="flex items-center gap-1.5 text-xs">
            <div className="w-2 h-2 rounded-full bg-green-400 animate-pulse" />
            <span className="text-green-400 font-mono">{stats.active} active</span>
          </div>
          <button
            onClick={fetchRules}
            className="p-1.5 rounded-lg hover:bg-slate-800 text-slate-500 hover:text-slate-300 transition-colors"
          >
            <RefreshCw className="w-3.5 h-3.5" />
          </button>
        </div>
      </div>

      {/* Empty state */}
      {!loading && rules.length === 0 && (
        <div className="text-center py-10">
          <Shield className="w-8 h-8 text-slate-700 mx-auto mb-2" />
          <p className="text-slate-500 text-sm">No adaptive rules yet.</p>
          <p className="text-slate-600 text-xs mt-1">
            Rules are generated automatically after Claude analyses a CRITICAL or HIGH severity threat.
          </p>
        </div>
      )}

      {/* Loading */}
      {loading && (
        <div className="space-y-2">
          {[1, 2, 3].map((i) => (
            <div key={i} className="h-14 rounded-xl bg-slate-800/50 animate-pulse" />
          ))}
        </div>
      )}

      {/* Active rules */}
      {activeRules.length > 0 && (
        <div className="space-y-2 mb-4">
          {activeRules.map((rule) => (
            <div
              key={rule.rule_id}
              className="flex items-start gap-3 bg-slate-800/50 rounded-xl border border-slate-700/40 p-3 group"
            >
              {/* Left: status dot */}
              <div className="w-2 h-2 rounded-full bg-green-400 mt-1.5 flex-shrink-0" />

              {/* Middle: content */}
              <div className="flex-1 min-w-0">
                <div className="flex items-center gap-2 flex-wrap mb-1">
                  <span className={`text-xs font-mono px-1.5 py-0.5 rounded border ${severityColor(rule.severity)}`}>
                    {rule.severity}
                  </span>
                  <span className="text-xs text-purple-400 font-mono">{rule.attack_type}</span>
                  <span className="text-xs text-slate-600 font-mono ml-auto">#{rule.rule_id}</span>
                </div>
                <code className="block text-xs text-cyan-300 font-mono bg-slate-950/60 rounded px-2 py-1 truncate">
                  {rule.pattern}
                </code>
                <div className="flex items-center gap-3 mt-1.5 text-xs text-slate-600">
                  <span>added {timeAgo(rule.created_at)}</span>
                  {rule.match_count > 0 && (
                    <span className="text-orange-400">
                      {rule.match_count} match{rule.match_count !== 1 ? "es" : ""}
                    </span>
                  )}
                  {rule.match_count === 0 && (
                    <span className="text-slate-700">no matches yet</span>
                  )}
                </div>
              </div>

              {/* Right: delete */}
              <button
                onClick={() => handleDelete(rule.rule_id)}
                disabled={deleting === rule.rule_id}
                className="p-1.5 rounded-lg opacity-0 group-hover:opacity-100 hover:bg-red-900/40 text-slate-600 hover:text-red-400 transition-all flex-shrink-0"
                title="Remove rule"
              >
                {deleting === rule.rule_id ? (
                  <RefreshCw className="w-3.5 h-3.5 animate-spin" />
                ) : (
                  <Trash2 className="w-3.5 h-3.5" />
                )}
              </button>
            </div>
          ))}
        </div>
      )}

      {/* Rejected rules (collapsed) */}
      {rejectedRules.length > 0 && (
        <div className="mt-3 pt-3 border-t border-slate-800">
          <p className="text-xs text-slate-600 flex items-center gap-1">
            <AlertCircle className="w-3 h-3" />
            {rejectedRules.length} rejected rule{rejectedRules.length !== 1 ? "s" : ""} (removed from filter)
          </p>
        </div>
      )}

      {/* Footer explanation */}
      {rules.length > 0 && (
        <div className="mt-3 pt-3 border-t border-slate-800 text-xs text-slate-600 leading-relaxed">
          Rules reload into Layer 1 every 30s · Hover a rule to delete it
        </div>
      )}
    </div>
  );
}
